### ISSUE TITLE
fundo sutil

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/calamar-io.github.io#1]
sobre a proposta de estudar alternativas ao fundo branco chapado, estive dando uma navegada em http://subtlepatterns.com/ e testando alguns, vou jogar aqui nos comentarios os links + screenshots

**Comment by fczuardi** [comment]
Crossword, http://subtlepatterns.com/crossword/

![screen shot 2016-03-23 at 1 15 49 pm](https://cloud.githubusercontent.com/assets/7760/13992151/b8fb04c0-f0f9-11e5-94a9-db6aa4c4475f.png)

**Comment by fczuardi** [comment]
Cream Dust, http://subtlepatterns.com/ı
![screen shot 2016-03-23 at 1 28 36 pm](https://cloud.githubusercontent.com/assets/7760/13992519/2a1a3742-f0fb-11e5-902f-9978847e3425.png)
cream_dust/

**Comment by fczuardi** [comment]
Subtle Dots http://subtlepatterns.com/subtle-dots/

![screen shot 2016-03-23 at 1 32 14 pm](https://cloud.githubusercontent.com/assets/7760/13992640/ac24317a-f0fb-11e5-8586-8ddcd2560a5a.png)

Absurdity http://subtlepatterns.com/absurdity/

![screen shot 2016-03-23 at 1 35 30 pm](https://cloud.githubusercontent.com/assets/7760/13992769/1fe9f7d4-f0fc-11e5-833d-2b26709dffe0.png)

Brilliant http://subtlepatterns.com/brilliant/

![screen shot 2016-03-23 at 1 36 43 pm](https://cloud.githubusercontent.com/assets/7760/13992850/6a93daf2-f0fc-11e5-8db2-15c7735744d2.png)

**Comment by thiagochristof** [comment]
Fechando porque mudamos a linha geral do design, valeu pelas sugestões ;)
